---
title: "E_Major_Theme"
author: "邱奕勳"
date: "2020/5/14"
output: html_document
---
```{r}
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext);library(grid);library(readxl);library(gridExtra)
font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
```

```{r}
indicator <- read_excel("~/Desktop/indicator.xlsx")
indicator$年月 %>% ymd() ->indicator$年月
```


#底圖
```{r}
indicator%>%ggplot(aes(x=indicator$年月))+
  geom_hline(yintercept = 100, color="black", linetype="longdash" , size =0.3)+ #標準線
  geom_line(aes(y=indicator$領先指標),color="#1f78b4",size=1.5)+ #geom
  geom_line(aes(y=indicator$同時指標),color="#33a02c",size=1.5)+
  geom_line(aes(y=indicator$落後指標),color="#d95f02",size=1.5)+
  labs(x="",y="",title = "景氣指標", subtitle = "單位：點")+ #兩標、title
  scale_y_discrete(limits = c(97:103), position = "right")+
  scale_x_date(
      breaks = seq(as.Date("2019-05-01"), as.Date("2020-03-01"), by="2 month"),
      labels = c("201905","07","09","11","202001","03")
      )->baseplot

baseplot
```

```{r}
baseplot+theme(
  plot.background = element_blank(),
  plot.margin = margin(30,0,0,20), #margin?
  plot.subtitle = element_text(size = 10, color = "#7c8290"),
  panel.background = element_blank(),
  panel.grid.major.y = element_line(color = "gray", size = 0.2),
  panel.grid.major.x = element_blank(), 
  axis.ticks.y = element_blank(),
  axis.line.y = element_blank(),
  axis.text.x = element_text(hjust = -0.1, vjust = 1.5),
  axis.line.x = element_line(color = "black"),
  axis.ticks.length = unit(3.5,"pt")
)-> modifiedP
modifiedP
```
#grid
```{r}
sources <-"sources: 國發會景氣指標查詢系統"
grid.arrange(
  modifiedP,
  bottom = textGrob(
    sources, x = 0.17 ,gp = gpar(fontface = 3L, fontsize = 9, col="#7c8290")
    ))
```


```{r}
sources <-"sources: 國發會景氣指標查詢系統"
grid.arrange(
  modifiedP, #graph
  bottom = textGrob( #bottom sources
    sources, x = 0.17 ,gp = gpar(fontface = 3L, fontsize = 9, col="#7c8290")
    ),
  top = rectGrob( #top tag
    x = 0, y = 1, width = 0.05,just = c("left","top"), height = 0.2, gp = gpar(fill="red")))


  
```

```{r}
sources <-"sources: 國發會景氣指標查詢系統"
grid.arrange(
  modifiedP, #graph
  bottom = textGrob( #bottom sources
    sources, x = 0.17 ,gp = gpar(fontface = 3L, fontsize = 9, col="#7c8290")
    ),
  top = rectGrob( #top tag
    x = 0, y = 1, width = 0.05,just = c("left","top"), height = 0.2, gp = gpar(fill="red")),arrangeGrob(modifiedP), ncol=2)
  
```

```{r}
library(grid)

my_rect <- rectGrob(x = 0, y = 0.995, width = 0.02,just = c("left","top"), height = 0.05, gp = gpar(fill="#E74C3C", col = "red"))

my_line <- linesGrob(x = unit(c(0.1, 1), "npc"),
          y = unit(c(0, 0.9), "npc"),
          default.units = "npc",
          gp=gpar(color = "black"))

my_srect <-rectGrob(x = 0, y = 0.995, width = 1,just = c("left","top"), height = 0.003, gp = gpar( fill = "#E74C3C", col = "red"))

sources <-"sources: 國發會景氣指標查詢系統"

my_text <- textGrob( #bottom sources
    sources, x = 0.17,y=0.02 ,gp = gpar(fontface = 3L, fontsize = 9, col="#7c8290")
    )
grid.newpage()+grid.draw(my_srect)
```

```{r}
grid.draw(modifiedP)+grid.draw(my_rect)+grid.draw(my_srect)+grid.draw(my_text) -> p2

p2
dev.off()
```

```{r}
grid.arrange(modifiedP ,modifiedP,ncol=2)+grid.draw(my_rect)+grid.draw(my_srect)+grid.draw(my_text)
```

```{r}
grid.arrange(modifiedP ,arrangeGrob(modifiedP),ncol=2)
```
```{r}
grid.arrange(modifiedP, modifiedP, ncol =2)
arrangeGrob(modifiedP, modifiedP, ncol = 2) ->ptest
ggsave(filename = "p.pdf", ptest)
```

```{r}
save(ptest, file = "myplottest.png")
```

```{r}
class(p2)
class(my_line)
```

